import { createRequire } from 'node:module';
const require = createRequire('/home/ubuntu/spends-ledger/');
const { chromium } = require('playwright');
const [BASE, PASSCODE, hash, out] = process.argv.slice(2);
const b = await chromium.launch({ executablePath: '/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux-arm64/chrome', args: ['--no-sandbox'] });
const page = await (await b.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
page.on('pageerror', (e) => console.log('PAGEERR', e.message, e.stack?.split('\n')[1])); page.on('console', (m) => console.log('CONSOLE', m.type(), m.text()));
await page.goto(BASE + '/'); await page.fill('#passcode', PASSCODE); await page.click('#go'); await page.waitForSelector('.picker');
await page.locator('.picker-card').first().click(); await page.waitForSelector('.topbar');
await page.goto(BASE + '/' + hash); await page.waitForTimeout(2500);
if (out) await page.screenshot({ path: out });
await b.close();
